### ISSUE TITLE
plaidml-keras not available? and few more questions.

### ISSUE THREAD

**Issue by itsnarsi** [plaidml/plaidbench#1]
Hey there! 
I started following your work when your CEO posted a thread on tensorflow opencl issue#22 saying you guys are working on implementing opencl version of keras.

Today I saw the blog post and tried to install plaid-keras using pip, but it says there is no version that satisfies the PC requirement.

>   Could not find a version that satisfies the requirement plaidml-keras (from versions: )
>    No matching distribution found for plaidml-keras

I also have few question I would like to ask you guys:
- Are you guys working on adding MIopen to your framework?
- It looks like plaid is private project. Are there any plans to make it public?
- What version of keras dose plaid uses 1.x or 2.x?

All that asked, great work guys! keep it up!

**Comment by choongng** [comment]
Hello, thanks! Great questions. 

First, the plaid-keras package is not yet available but we do plan to make it public. We are actively working on getting it ready to open source, the gate for release is a good enough user experience that many users can work through a convnet vision tutorial. I don't think it's too far off but the exact timing will be driven by when we have the quality we want to deliver. We will make both source and binaries available.

With respect to framework support, today we use Keras 2. Our future development will be driven by education and research requirements. AMD is doing good work with MIOpen but we have gotten more questions about support for TensorFlow and PyTorch than anything else.

What kind of workload do you need to support?

**Comment by itsnarsi** [comment]
I am a PhD student with Biometrics as my reserach area. Biggest deep learning model we deal with 
ResNet-50.
 I use tensorflow a lot and some times Keras for my work.

Currently I use a RX 480 (arrayfire for compute) and also have university PC with GTX 1070.

I am looking to buying amd vega gpu if there is any framework support available with in two weeks. If not, I was thinking to go with GTX 1080 ti.

**Comment by choongng** [comment]
Very cool, ResNet-50 is part of our standard test run. Vega doesn't have FP16 driver support yet but once they do they'll probably be about 2x as fast as a 1080 Ti. Really good for $700. If you'd like to try a pre-release version of our open source code send a mail to info@vertex.ai, we'll get you set up.

**Comment by itsnarsi** [comment]
Nice! I'll send an email as soon as possible. 
It would be also cool to have benchmark on a vega card, so we can see how well it performance compared to GTX 1080ti.

Sorry for late reply. Lot of deadlines.

**Comment by itsnarsi** [comment]
Hey @choongng , I sent an email at info@vertex.ai
Is it possible to set me up soon?

Thanks

**Comment by choongng** [comment]
Hello @itsnarsi yes, check your e-mail. Thanks!

**Comment by nicezic0** [comment]
When it will be released? Could you let me know the approximate date?

**Comment by choongng** [comment]
@nicezic0 it is coming very soon, we are in the final stretch of getting the everything ready for collaborators. If you send a note to info@vertex.ai we can send you one a preview build sooner though. What kind of GPU & workload are you interested in?

**Comment by choongng** [comment]
plaidml-keras is now installable via pip! Source code is also available: 
- https://github.com/plaidml/plaidml
- http://vertex.ai/blog/announcing-plaidml
