### ISSUE TITLE
Instructions in the tensorcomp branch are broken

### ISSUE THREAD

**Issue by masahi** [plaidml/plaidbench#49]
Hi, I just read your blog about comparing tensor compilers, and I want try the same benchmark on my cards (GTX 1070 Ti and R9 Nano). 

I tried following instructions [here](https://github.com/plaidml/plaidbench/tree/tensorcomp), but I am getting 'No such option' errors everywhere, something like:
`Error: no such option: --results`
`Error: no such option: --tc`

Can you fix the instructions there?

**Comment by brianretford** [comment]
It's very specific about where you put the options, what exact commands are
you running?

**Comment by brianretford** [comment]
They've been updated, please let me know if you have any other issues and we'll be them fixed post-haster

**Comment by masahi** [comment]
Ah, I forgot to do `python setup.py install` in the tensorcomp branch. I installed the master branch earlier.
Thanks, it's working now.
